on:
  pull_request_review_comment:
    types: [ created, deleted ]

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
      - name: Send GitHub trigger payload to Slack Workflow Builder
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Danny Torrence left a 1 star review for your property.",
              "blocks": [{
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Danny Torrence left the following review for your property:"
                }
              }]
            }
        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK